### ISSUE TITLE
JupyterHub demonstration server for the project review

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/OpenDreamKit#296]
@minrk  is setting up a demo VRE (JupyterHub) for running demos during the final project review. 
Soon there will be a separate repository; this issue is for discussing the matter in the mean time.

**Comment by nthiery** [comment]
> where is opendreamkit.org DNS? It would probably be nice to make the Hub accessible at e.g. review-hub.opendreamkit.org rather than something at minrk.net.

The registrar is Gandi, and I am owning the domain opendreamkit.org. I can easily setup a subdomain
once given a target IP. I suggest review-vre.opendreamkit.org.

**Comment by nthiery** [comment]
@ClementPernet, @minrk: about this server and WP5 demos

At the previous review, we had setup a Jupyter(Hub?) server to run the WP5 demonstrations. The technical setup was a many core (32? 64?) linux virtual machine running on Orsay's cloud, where each piece of software was installed manually, often with some custom build. We need to decide whether we could use review-vre.opendreamkit.org for the WP5 demos as well or whether the requirements are two stringent and require a separate box.

Here is a preliminary list of requirements for WP5 demos:
- Run on a many-core machine to demonstrate multithreaded applications
- Enable custom build of some of the software; which may require several install of the same software
- ... (please edit)

I assume that @minrk is planning for an automated deployment, with a Docker file describing the Jupyter image. Is this flexible enough for the custom build?

@ClementPernet: could you post here the instructions you collected with Vincent when deploying the previous server?

**Comment by nthiery** [comment]
> I assume since this for the review, it is okay to bill the costs (both the hosting costs and my time spent on it) to ODK, based on comments we received previously?

From the scientific perspective, yes, this definitively makes sense. From the administrative side, please double check with Katarina.

**Comment by minrk** [comment]
> Is this flexible enough for the custom build?

Yes, absolutely. Just need the commands to run. I can also do a deployment with multiple images/profiles if that makes more sense.

**Comment by alex-konovalov** [comment]
GAP demos are at https://github.com/OpenDreamKit/gap-demos and you can see setup in the Dockerfile there.

(Will a checklist in the description of this issue be helpful?)

**Comment by nchauvat** [comment]
Hi ODK,

On Sat, Oct 05, 2019 at 12:52:03AM -0700, Nicolas M. Thiéry wrote:

> I assume that @minrk is planning for an automated deployment, with a
> Docker file describing the Jupyter image. Is this flexible enough
> for the custom build?

At Logilab, we deployed last week our new jupyterhub server on top of
kubernetes at OVH with images taken from our docker registry.

If we can help with the deployment of the jupyterhub server for the
demo at the end of the month, please let us know.

Regarding the work we did in the project concerning training scientist
to python, we would like to make available a docker image with
"jupyter-training" installed.

-- 
Nicolas Chauvat

logilab.fr - services en informatique scientifique et gestion de connaissances

**Comment by minrk** [comment]
I've launched a demo cluster at https://odk-review.minrk.net. @nthiery the IP is 34.77.130.182 if you want to create DNS on opendreamkit.org. It should have a wildcard record, so that `*.review-vre.opendreamkit.org` resolves to this IP. In my registrar (Hover), I use one A record and one CNAME record:

```
A odk-review.minrk.net 34.77.130.182
CNAME *.odk-review.minrk.net odk-review.minrk.net
```

**Comment by nthiery** [comment]
> I've launched a demo cluster at https://odk-review.minrk.net.

Thanks for the progress!

> @nthiery the IP is 34.77.130.182 if you want to create DNS on opendreamkit.org.

Done. Please test.

**Comment by minrk** [comment]
The image is based on `registry.gitlab.com/sagemath/sage/sagemath:9.0.beta0-py3` so that's where it's getting GAP. If there's another, better way to get GAP, I'd be happy to add that.

One thing I'm not sure about is whether we want separate images for the demos or one big image. One big image is a little easier to manage, but I can make separate images work as well.

The reason it's prompting is that Sage installs the gap kernel with a different name than the GAP image. This shouldn't prompt since there's only one match for language: gap, but it's something not yet implemented in jupyterlab. If the kernelspec names matched, this wouldn't happen.

**Comment by minrk** [comment]
I updated the image so that the gap demos don't prompt  for kernel choice.

A helpful pointer to what gap packages should be installed and how to install them in a sage gap install would be awesome.

**Comment by pdehaye** [comment]
FYI I just tried logging in with Github and I got a "400 : Bad Request OAuth state missing from cookies"
I don't know if it worked before.

**Comment by nthiery** [comment]
@minrk: do you have a Dockerfile or similar to which we can propose pull-requests to add bits and pieces to be installed on the demo server?

**Comment by alex-konovalov** [comment]
@minrk we have a GAP Docker container at https://hub.docker.com/r/gapsystem/gap-docker/ which is quite complete. Is there a way to use that for GAP demos?

**Comment by defeo** [comment]
> FYI I just tried logging in with Github and I got a "400 : Bad Request OAuth state missing from cookies"
> I don't know if it worked before.

Maybe you visited odk-review.minrk.net instead of https://review-vre.opendreamkit.org/ ?

**Comment by defeo** [comment]
> I updated the image so that the gap demos don't prompt for kernel choice.
> 
> A helpful pointer to what gap packages should be installed and how to install them in a sage gap install would be awesome.

The Semigroups notebook is not working because of a missing Semigroups package. So, at least that one.

Also, Singular behaves funny:
![Screenshot_2019-10-18 JupyterLab](https://user-images.githubusercontent.com/1315842/67091443-e9c23a80-f1ac-11e9-9cdb-80351087efcd.png)

**Comment by tthsqe12** [comment]
`1+1` is a syntax error in singular. You need `1+1;`.
For my demonstration, I will need a custom installation of singular and flint. Will this we easy to incorporate into what you all already have?

**Comment by tthsqe12** [comment]
@nthiery I am finding the jupyter interface for singular to be uncomfortable at best and unusable at worst. Would it be possible to demonstrate that the jupyter interface to singular does exist, but do the actual demonstration using the command line?

**Comment by defeo** [comment]
> `1+1` is a syntax error in singular. You need `1+1;`.

Well, then it's weird that it gets evaluated nevertheless

> For my demonstration, I will need a custom installation of singular and flint. Will this be easy to incorporate into what you all already have?

As long as you have a Dockerfile, I guess yes.

**Comment by nthiery** [comment]
> @nthiery I am finding the jupyter interface for singular to be
> uncomfortable at best and unusable at worst. Would it be possible to
> demonstrate that the jupyter interface to singular does exist, but
> do the actual demonstration using the command line?

Well, we motivated our work on performance by saying it would benefit
our Virtual Research Environments. For the later, our primary user
interface is Jupyter. So running the demo in Jupyter would better
support our general story.

That being said, it's better to have a good demo on the command line
than a lame demo in Jupyter.

So I suggest that:

- You define somewhere the hurdles that make the Jupyter interface for
  Singular "uncomfortable at best and unusable at worst" for you.
  Maybe in the form of a series of issues on:

        https://github.com/sebasguts/jupyter_kernel_singular/issues

  In particular, is that about Jupyter in general for the kind of demo
  you want to run? Or about limitations of the current kernel?

- You prepare a compelling demo on the Singular command line for now,
  to be run within a terminal in the JupyterHub server.

- We check whether there is anything we can do on the Jupyter
  interface side to mitigate the hurdles. Presumably this is too late
  at this stage, and we have to live with the fact that this should
  have been experimented with earlier. But if we are lucky and can
  switch back to Jupyter at the end, so much the better.

**Comment by tthsqe12** [comment]
I have worked around the issues in my notebook, so it should be fine for demonstration. It's not perfect, but it will work.

**Comment by nthiery** [comment]
> I have worked around the issues in my notebook, so it should be fine
> for demonstration. It's not perfect, but it will work.

Ok; nice.

Still, please report on the specific issues or annoyances you faced;
this is very valuable user experience!

**Comment by tthsqe12** [comment]
Ok. Is it easy to lengthen the timeout period? It looks like something is killing the calculation if it goes longer than ~45 seconds.

**Comment by nthiery** [comment]
> Ok. Is it easy to lengthen the timeout period? It looks like something is killing the calculation if it goes longer than ~45 seconds.

No idea. @sebasguts?

**Comment by minrk** [comment]
The repo is at https://github.com/opendreamkit/odk-review-hub if folks want to make pull requests. It's currently being built and updated from my machine, but I hope to have it being pushed automatically from CI on merge on Tuesday. There are now two images in there, a default image based on `sagemath:9.0.beta0-py3` and a gap image based on `gapsystem/gap-docker`. The image is selected at launch time. Adding more separate images is easy if folks have Dockerfiles or images they would like to use.

**Comment by tthsqe12** [comment]
@minrk I have do idea what a docker is. What I will need is a standard installation of the latest `wbhart/flint2/trunk` and an installation of the latest `Singular/Sources/spielwiese` with the option `--disable-omalloc`. Do you have a good docker tutorial you can point me to? Supposing that I am able to make a docker, how/where would I go about testing it?

**Comment by minrk** [comment]
@tthsqe12 if you can provide me shell commands to perform the installation, I can update the image. A Dockerfile is basically a sequence of shell commands used to install files and then the result is saved as an 'image'. The current [Dockerfile is here](https://github.com/OpenDreamKit/odk-review-hub/blob/master/images/singleuser/Dockerfile). If you have an install script to download and install the packages, adding it to the image will be easy for me to do, if you don't want to learn the docker tools right now. If you do want to learn docker, [this tutorial](https://ome.github.io/training-docker/) seems good, and there are many more online.

**Comment by tthsqe12** [comment]
@minrk I have uploaded our notes from the workshop into the readme.md for my repo at
https://github.com/tthsqe12/SingularParallelArithmetic

**Comment by minrk** [comment]
@tthsqe12 thanks, that should be enough. I think I have it working, will upload a new image tomorrow.

**Comment by tthsqe12** [comment]
Thank you! I look forward to possibly trying it out.

**Comment by ClementPernet** [comment]
HI,
I just gave it a try to see how the performances of the parallelized sage-linbox interface was:
 * the computation speed of sage is surprisingly low :  matrix product over GF(65521) takes 15sec for 2000x2000 matrices (compared to 0.617sec on my laptop with the same micro-arch). Is this because of some use of virtualization?
 * Then parallelization is also quite disapointing: on using 2 cores shrinks this time from 15s to 10.4s, and on 4 cores it takes: 17s! 
For demonstrating this set of deliverables, I think we should aim at a server with many more cores (ideally 32, or 64).

If there is no easy way to fix these issues, we might want to consider using a dedicated multicore server for this demo (like the VM from UPSUD which @nthiery did setup last year).

**Comment by minrk** [comment]
I can provide more resources as desired. Currently it's very limited during setup, but I can make much more available. I'll add profiles with more cores available.

**Comment by minrk** [comment]
I've updated the server with the requested custom builds of singular and some more profiles. I can easily add more if folks want them, I just need to know what people want.

There is now an 'hpc' node pool, where each node has 32 cores and a profile to use this pool with either the custom Singular build or the default sage image. If folks have some benchmarks they would like to run, I can test those out.

I've no objection if folks want to use a dedicated deployment for hpc demos.

**Comment by alex-konovalov** [comment]
@minrk that's great. If we want to install HPC-GAP there (there is no Docker container for it), how do we proceed? If you wish to build it manually, then follow section "Building HPC-GAP" from https://github.com/gap-system/gap/wiki/Building-HPC-GAP and then do

    make bootstrap-pkg-full
    cd pkg
    ../bin/BuildPackages.sh

to download and build GAP packages.

**Comment by minrk** [comment]
I'm happy to build hpc-cap. Should that replace the existing gap image, or be added as a new image?

**Comment by alex-konovalov** [comment]
Thanks - only as new please !!!

**Comment by minrk** [comment]
@alex-konovalov I was able to build hpcgap following the instructions at that link, but the kernel's not starting:

```
GAP Jupyter Kernel Starting using /opt/gap/bin/gap.sh
#I  DeclareGlobalFunction: too many arguments in /opt/gap/pkg/crisp-1.4.4/lib/util.gd:16
Error, BIND_GLOBAL: variable `SynchronizationFamily' must be unbound at /opt/gap/lib/global.g:138 called from
BIND_GLOBAL( name, value ); at /opt/gap/lib/global.gi:268 called from
<function "BindGlobal">( <arguments> )
 called from read-eval loop at /opt/gap/pkg/ZeroMQInterface-0.11/gap/zmq.g:14

Error, was not in any namespace at /opt/gap/hpcgap/lib/variable.g:343 called from
LEAVE_NAMESPACE(  ); at /opt/gap/lib/package.gi:1298 called from
<function "ReadPackage">( <arguments> )
 called from read-eval loop at /opt/gap/pkg/ZeroMQInterface-0.11/init.g:20

Error, was not in any namespace at /opt/gap/hpcgap/lib/variable.g:343 called from
LEAVE_NAMESPACE(  ); at /opt/gap/lib/package.gi:1298 called from
ReadPackage( pkgname, "init.g" ); at /opt/gap/lib/package.gi:1665 called from
<function "LoadPackage">( <arguments> )
 called from read-eval loop at stream:1

Error, Variable: 'JUPYTER_KernelStart_GAP' must have a value
not in any function at stream:2

Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `Remove' on 1 arguments at /opt/gap/lib/methsel2.g:249 called from
Remove( GAPInfo.AtExitFuncs ) at /opt/gap/lib/session.g:31 called from
<function "PROGRAM_CLEAN_UP">( <arguments> )
 called from read-eval loop at /opt/gap/lib/init.g:1022
```

Is there perhaps a particular revision rather than master that I should build?

**Comment by alex-konovalov** [comment]
@minrk more complicated:

1. do `git pull` to get just merged https://github.com/gap-system/gap/pull/3710

2. Call `make` in GAP root directory 

2. in `pkg/ZeroMQInterface-*`, apply https://github.com/gap-packages/ZeroMQInterface/commit/d102075feba05d2cfa06c339bb1ceaffc2302309

3. rebuild `ZeroMQInterface` package: `make clean; ./configure; make`

4. Start GAP with `-r -A -S` options. For example, this is what I have in by `~/.bash_profile`: 

    export JUPYTER_GAP_EXECUTABLE="/Users/alexk/GITREPS/hpcgap/bin/gap.sh -r -A -S"

**Comment by tthsqe12** [comment]
I am sorry that I am very lost. Is it possible to try out at this time an approximation of the setup we will be using? I suppose that I will have a browser window open on my local machine here, and that it will be communicating with some other entity somewhere. How can I make this happen?

**Comment by tthsqe12** [comment]
@minrk Is there any way I can try what you have set up for me from a jupyter notebook interface and/or command line interface?

**Comment by alex-konovalov** [comment]
@minrk if have installed HPC-GAP, is Jupyter the only way to access it? Will we be able to log in and demonstrate it in the terminal interface too? CC @stevelinton

**Comment by nthiery** [comment]
> @minrk if have installed HPC-GAP, is Jupyter the only way to access
> it? Will we be able to log in and demonstrate it in the terminal
> interface too? CC @stevelinton

Yup; in both Jupyter and JupyterLab, you can always open a terminal,
and be back home. See around the File -> Open menu or Launcher.

**Comment by alex-konovalov** [comment]
@minrk in which case, where the directory with HPC-GAP is located?

**Comment by alex-konovalov** [comment]
@minrk we need to install one more package, not yet redistributed with GAP, into GAP 4.10.2 installation (not the HPC-GAP one). The package is https://gap-packages.github.io/meataxe64/, it requires compilation, and there is some other change you will have to made in its code before compiling it - @stevelinton can tell you which.

**Comment by stevelinton** [comment]
@minrk In `meataxe64` there is a file `src/mtx64/tuning.h`. If you change `THREADS` to one or two less than the number of hyperthreads on the vitrtual machine and `MEGABYTES` to  a bit less than the total memory,  before compiling, that should work well.

**Comment by minrk** [comment]
@tthsqe12 yes, visit https://review-vre.opendreamkit.org and login with github. There you can pick an environment and test it out. Singular Parallel has 32 cores available. Upon logging in, you have access via notebook or terminal within JupyterLab. 

@alex-konovalov thanks, I will update the gap and hpcgap images with this feedback and report back here.

> in which case, where the directory with HPC-GAP is located?

In `/opt/gap`, also available as $GAPROOT and on $PATH

@stevelinton when I try to install meataxe64 v0.1, it fails with:

```
  CC       src/meataxe64_la-meataxe64.lo
src/meataxe64.c: In function 'FuncMTX64_Make8BitConversion':
src/meataxe64.c:689:59: error: macro "FFE_FELT_FIELDINFO_8BIT" passed 2 arguments, but takes just 1
       FFV ent2 = VAL_FFE(FFE_FELT_FIELDINFO_8BIT(info,ent));
                                                           ^
In file included from /home/gap/inst/gap-4.10.2/src/compiled.h:30:0,
                 from src/meataxe64.h:5,
                 from src/meataxe64.c:12:
src/meataxe64.c:689:26: error: 'FFE_FELT_FIELDINFO_8BIT' undeclared (first use in this function)
       FFV ent2 = VAL_FFE(FFE_FELT_FIELDINFO_8BIT(info,ent));
                          ^
/home/gap/inst/gap-4.10.2/src/finfield.h:315:48: note: in definition of macro 'VAL_FFE'
 #define VAL_FFE(ffe)            ((FFV)(((UInt)(ffe)) >> 16))
                                                ^~~
src/meataxe64.c:689:26: note: each undeclared identifier is reported only once for each function it appears in
       FFV ent2 = VAL_FFE(FFE_FELT_FIELDINFO_8BIT(info,ent));
                          ^
/home/gap/inst/gap-4.10.2/src/finfield.h:315:48: note: in definition of macro 'VAL_FFE'
 #define VAL_FFE(ffe)            ((FFV)(((UInt)(ffe)) >> 16))
                                                ^~~
src/meataxe64.c: In function 'FuncMTX64_RANDOM_MAT':
src/meataxe64.c:832:5: warning: implicit declaration of function 'RequireStringRep'; did you mean 'CopyToStringRep'? [-Wimplicit-function-declaration]
     RequireStringRep("MTX64_RANDOM_MAT", mtsource);
     ^~~~~~~~~~~~~~~~
     CopyToStringRep
make: *** [src/meataxe64_la-meataxe64.lo] Error 1
```

To reproduce this, I ran the dockerfile:

```Dockerfile
FROM gapsystem/gap-docker@sha256:77f8f263363b805612ca076a54f1b111238af0e544ab2740c05129f44e6f284e

RUN cd $GAP_HOME/pkg \
 && wget https://github.com/gap-packages/meataxe64/releases/download/v0.1/meataxe64-0.1.tar.gz \
 && tar -xzf meataxe64*.tar.gz \
 && cd meataxe64* \
 && ./autogen.sh \
 && ./configure --with-gaproot=$GAP_HOME \
 && make
```

are there other modifications needed to build with gap 4.10.2?

**Comment by tthsqe12** [comment]
@minrk Thank you for letting me know. The address https://review-vre.opendreamkit.org/ currently responds with "Service Unavailable". Will it be available soon?

**Comment by minrk** [comment]
@tthsqe12 yes, it's up now. That error occurs while the configuration is being updated and should only ever be the case for less than a minute at any given time.

**Comment by stevelinton** [comment]
@minrk The current version of the package works with GAP master from github. Do we have that in the VM already? If not I'll see if there's an easy backwards compatibility fix.

**Comment by alex-konovalov** [comment]
@minrk @stevelinton We have docker container for GAP master branch - shall we use it for demos of meataxe64 package only? It's here: https://hub.docker.com/r/gapsystem/gap-docker-master/ and is built nightly (works fine now, we will have to fix it's version by sha256).

**Comment by stevelinton** [comment]
@alex-konovalov @minrk That container seems to work if you just clone current master of `meataxe64` into the `pkg` directory, so that seems like a good strategy. My quick attempt to reverse the changes to `meataxe64` that track GAP changes since 4.10 seem to have broken something else. Can we set up that container with `meataxe64` as a kernel option for our demo worksheets?  Can docker use multiple cores?

**Comment by stevelinton** [comment]
@minrk @alex-konovalov We're going to need gap master to demo syntaxtree as well.

**Comment by minrk** [comment]
I updated the gap image to latest gap-docker-master, and the install is going fine. I'm pushing the updated GAP image now.

> Can we set up that container with meataxe64 as a kernel option for our demo worksheets?

Yes, if you pick the GAP environment, it will now have GAP master and meataxe64.

> Can docker use multiple cores?

Yes, the default for the GAP image is to run with a 4 core limit, but we can run with as many as you want. I haven't received any feedback yet on what resources people need other than the HPC demos wanting 32 or 64 cores. 

> shall we use it for demos of meataxe64 package only?

I replaced the existing GAP environment with master. If you need GAP stable that is distinct from the GAP 4.10 in the default Sage image, we can create another image.

**Comment by tthsqe12** [comment]
@minrk Thank you! That seems to be working well enough up to 16 threads except for random kernel deaths. Would you expect the kernel link to die if the calculation takes too much time/memory? @nthiery This new interface to singular does not seem to be suffering from the usability issues that I was experiencing on my local machine. It must have been something I installed wrong on my end.

**Comment by minrk** [comment]
> Would you expect the kernel link to die if the calculation takes too much time/memory? 

memory limit is very likely culprit. I hadn't bumped it past 2G yet. What's a reasonable limit? The Singular Parallel and HPC GAP limits are now 16G

**Comment by alex-konovalov** [comment]
@minrk @stevelinton I've submitted https://github.com/OpenDreamKit/odk-review-hub/pull/5 - apparently @rbehrdends made the fix in https://github.com/gap-system/gap/pull/3715.

**Comment by nthiery** [comment]
> @nthiery This new interface to singular does not seem to be suffering from the usability issues that I was experiencing on my local machine. It must have been something I installed wrong on my end.

Great, good news!

**Comment by alex-konovalov** [comment]
@minrk as said above, you need to start HPC-GAP with `-r -A -S` options. For example, this is what I have in my ~/.bash_profile: 

    export JUPYTER_GAP_EXECUTABLE="/Users/alexk/GITREPS/hpcgap/bin/gap.sh -r -A -S"

Now if you will be rebuilding the Docker container at https://github.com/OpenDreamKit/odk-review-hub/blob/master/images/hpcgap/Dockerfile one more time, you will pull one more commit from https://github.com/gap-system/gap/pull/3715 which introduces `--single-thread` command line option. Please add it to GAP invocation in `JUPYTER_GAP_EXECUTABLE` then.
